POST http://localhost:3000/api/prompt
Content-Type: application/json

{
  "model": {
    "name": "mythomax-l2-13b.Q4_K_M.gguf",
    "type": "local_llm"
  },
  "prompt": "Test Prompt reply with Hello World"
}